services: 
  - docker
script: 
  - echo "success"
after_success:
  - docker build -t liran/multi-client ./client
  - docker build -t liran/multi-nginx ./nginx
  - docker build -t liran/multi-server ./server
  - docker build -t liran/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push liran/multi-client liran/multi-nginx liran/multi-server liran/multi-worker
after_failure:
  - echo "failure"