services: 
  - docker
script: 
  - echo "success"
after_success:
  - docker build -t iliran11/multi-client ./client
  - docker build -t iliran11/multi-nginx ./nginx
  - docker build -t iliran11/multi-server ./server
  - docker build -t iliran11/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push iliran11/multi-client
  - docker push iliran11/multi-nginx
  - docker push iliran11/multi-server
  - docker push iliran11/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-252150623009
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


