services: 
  - docker
script: 
  - echo "success"
after_success:
  - docker build -t iliran11/multi-client ./client
  - docker build -t iliran11/multi-nginx ./nginx
  - docker build -t iliran11/multi-server ./server
  - docker build -t iliran11/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push iliran11/multi-client
  - docker push iliran11/multi-nginx
  - docker push iliran11/multi-server
  - docker push iliran11/multi-worker
after_failure:
  - echo "failure"